# ╔══════════════════════════════════════════╗
# ║     NOTIFICATIONS STYLING                ║
# ╚══════════════════════════════════════════╝

# ╔══════════════════════════════════════════╗
# ║     VERCEL                               ║
# ╚══════════════════════════════════════════╝
# Style for command prompt and messages
# This is what you see when you type Prefix+: or when tmux shows messages
# Valid values: same as status-style
# set -g message-style "bg=default,fg=#49AEFF,bold"

# Style for command mode (when typing commands)
# Valid values: same as status-style
# set -g message-command-style "bg=#005BE7,fg=#FAFAFA"

# ╔══════════════════════════════════════════╗
# ║     VESPER                               ║
# ╚══════════════════════════════════════════╝
# Style for command prompt and messages
# This is what you see when you type Prefix+: or when tmux shows messages
# Valid values: same as status-style
# set -g message-style "bg=default,fg=#FFC799,bold"

# Style for command mode (when typing commands)
# Valid values: same as status-style
# set -g message-command-style "bg=#FFC799,fg=#101010"

# ╔══════════════════════════════════════════╗
# ║     SOLARIZED                            ║
# ╚══════════════════════════════════════════╝
# Style for command prompt and messages
# This is what you see when you type Prefix+: or when tmux shows messages
# Valid values: same as status-style
set -g message-style "bg=default,fg=#859900,bold"

# Style for command mode (when typing commands)
# Valid values: same as status-style
set -g message-command-style "bg=#859900,fg=#002B36"
